# Generated by Django 2.2.5 on 2019-10-04 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MusicalWork",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "contributors",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "iswc",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "T-?[0-9]{3}\\.?[0-9]{3}\\.?[0-9]{3}-?[0-9]"
                            )
                        ],
                    ),
                ),
            ],
            options={"db_table": "musical_works"},
        )
    ]
